### PR TITLE
PHP 8.1

### PR DESCRIPTION
**Pull request by tobias-trozowski**
- added support for php 8.1
- removed composer.lock
- fixed unit tests

### CODE REVIEW

**Comment by tobias-trozowski** [comment]
ping @rdohms 
i'd really appreciate if you had some time and can have a look into this so this package is also usable for php 8.1.

**Comment by rdohms** [comment]
Sorry @tobias-trozowski will try to get to it this week.

**Comment by rdohms** [comment]
@tobias-trozowski can you double check the Code style issues?
Did you find removing the lock had any effect? I like to keep lock files as a tool for contributors to know what they are coding against and reducing friction. Since we run a composer update in the tests the lock file should not interfere there only in devs running an install locally.

**Comment by tobias-trozowski** [comment]
IMO there's no use for the lock file here as we are testing against latest and lowest. it's just one more thing which can cause friction (e.g. merge conflicts).

**Comment by rdohms** [comment]
@tobias-trozowski its mostly for local testing and contributor experience.

**Comment by tobias-trozowski** [comment]
@rdohms so shall i revert the removal? IMO it's not needed but i'm happy to add it again if you want it back

**Comment by tobias-trozowski** [comment]
@rdohms commit removed

**Review by rdohms — APPROVED** [review]

**Comment by rdohms** [comment]
Released as 4.0.2, thanks!

**Comment by tobias-trozowski** [comment]
thanks a lot!

**Pull request merged**
